openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ARTHURSAITO/cielo-backend-challenge/1.0.0
info:
  version: "1.0.0"
  title: cielo-backend-challenge
  description: The API for backend-challenge in Cielo Bootcamp
paths:
  /clients:
    post:
      tags:
        - Clients
      summary: Create a client
      description: create a client
      operationId: createClients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientRequest"
      responses:
        '201':
          description: Client created successfully
        '409':
          description: Client already exists
        '400':
          description: Bad request Syntax error

  /clients/{uuid}:
    get:
      summary: returns information about a specific client
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Client data successfully return
        '404':
          description: Client not found
        '400':
          description: Bad request Syntax error

components:
  schemas:
    ClientRequest:
      oneOf:  # Usamos oneOf para especificar que o objeto deve atender a pelo menos uma das condições
        - $ref: "#/components/schemas/ClientLegalRequest"
        - $ref: "#/components/schemas/ClientFisicalRequest"

    ClientLegalRequest:
      type: object
      properties:
        category:
          type: string
          enum:
            - legal_client
        cnpj:
          type: string
          pattern: '^[0-9]{14}$'
        razao_social:
          type: string
          maxLength: 50
        mcc:
          type: string
          maxLength: 4
        cpf:
          type: string
          pattern: '^[0-9]{11}$'
        name:
          type: string
          maxLength: 50
        email:
          type: string
          pattern: '^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$'

          required:
            - category
            - cnpj
            - razao_social
            - mcc
            - cpf
            - name
            - email


    ClientFisicalRequest:
      type: object
      properties:
        category:
          type: string
          enum:
            - fisical_client
        mcc:
          type: string
          maxLength: 4
        cpf:
          type: string
          pattern: '^[0-9]{11}$'
        name:
          type: string
          maxLength: 50
        email:
          type: string
          pattern: '^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$'

          required:
            - category
            - cpf
            - mcc
            - name
            - email